// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import { PrismaClient } from ".prisma/client"

const prisma = new PrismaClient();

export default async (req, res) => {
    try {
        const createManyDaftarAkun = await prisma.user.createMany({
            data: [
                {
                    kode_akun: "6-60101",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pemeliharan Bangunan & Prasarana Jasa",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60102",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pemeliharan Bangunan & Prasarana Material",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60103",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perbaikan & Perawatan Perabot Jasa",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60104",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perbaikan & Perawatan Perabot Material",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60105",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "By Pemeliharaan Kend,A.Berat,Mesin-Pihak3 Jasa",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60106",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "By Pemeliharaan Kend,A.Berat,Mesin-Pihak3 Material",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60107",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Oli & Pelumas",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60108",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Pemakaian Sparepart Kend & A.Berat",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60109",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Gaji",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60110",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Tunjangan Lainnya",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60111",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya JAMSOSTEK (BPJS)",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60112",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Iuran Pensiun",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60113",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pengobatan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60114",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Internet",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60115",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya THR, Bonus, Liburan, dan Cuti ",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60116",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Dana Pensiun Past Service Liab.",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60117",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pengobatan di Luar",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60118",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Keamanan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60119",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Pengelolaan Tenaga Kerja",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60120",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "By Penggantian Pengelolaan Tenaga Kerja",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60121",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Seragam & Perlengkapan Kerja",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60122",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pesangon",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60123",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Tunjangan Perumahan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60124",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Air",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60125",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Listrik",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60126",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Gas",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60127",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60128",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi Pengangkutan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60124",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Air",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60125",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Listrik",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60126",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Gas",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60127",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60128",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi Pengangkutan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60124",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Air",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60125",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Listrik",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60126",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Gas",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60127",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60128",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Asuransi Pengangkutan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60129",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Sewa Bangunan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60130",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Pergudangan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60131",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Sewa Peralatan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60132",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Sewa Lahan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60133",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Kurir / Forwarder",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60134",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Pelayaran",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60135",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pajak Bumi dan Bangunan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60136",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pajak Kendaraan Bermotor",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60137",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perizinan Pemerintah",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60138",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Izin Tenaga Kerja",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60132",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Sewa Lahan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60133",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Kurir / Forwarder",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60134",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jasa Pelayaran",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60135",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pajak Bumi dan Bangunan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60136",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Pajak Kendaraan Bermotor",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60137",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perizinan Pemerintah",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60138",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Izin Tenaga Kerja",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60139",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Transportasi Lokal",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60140",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perjalanan Dalam Negeri",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60141",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perjalanan Luar Negeri",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60142",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Bahan Bakar",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60143",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Mess",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60144",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Jamuan / Representasi",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60145",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Olahraga Dan Permainan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60146",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Olahraga Dan Permainan",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60147",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Sumbangan Sosial",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60148",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Makanan dan Minuman",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60149",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perayaan dan Upacara",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60150",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perlengkapan Kantor",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60151",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Perlengkapan Fotocopy",
                    kategori: "Beban",
                    saldo: " ",
                },
                {
                    kode_akun: "6-60152",
                    nama: "Beban Administrasi dan Umum",
                    nama_akun: "Biaya Komunikasi",
                    kategori: "Beban",
                    saldo: " ",
                },
            {
                kode_akun: "6-60153",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Organisasi Professional Internasional",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60154",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Orgaanisasi Professional Nasional",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60155",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Pelatihan External Pihak ke-3",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60156",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Kursus Umum",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60157",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Pelatihan Internal Kantor",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60158",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Beasiswa",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60159",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Pencarian Tenaga Kerja",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60160",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Langgganan Buku, Jurnal, Koran,dan Lainnya",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60161",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Konferensi Lokal",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60162",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Konferensi di Luar Negeri",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60163",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Konferensi Internal",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60164",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Profesional",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60165",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Notaris / Hukum",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60166",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Perjalanan/Penggantian untuk Jasa Notaris/Hukum",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60167",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Audit",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60168",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Konsultan",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60169",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Perjalanan/ Penggantian untuk Konsultan",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60170",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Management",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60171",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Penyusutan Investaris Kantor",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60172",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Penyusutan Kendaraan",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60173",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Penyusutan Mesin",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60174",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Penyusutan Bangunan",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60175",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Amortisasi Penyusutan",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60176",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Administrasi Bank",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60177",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Dokumentasi",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60178",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Umum dan Administrasi",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60179",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Bebabn PPh 4 Ayat 2",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60180",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPh 21",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60181",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPh 23",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60182",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPh 25",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60183",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPh 26",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60184",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Denda Pajak",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60185",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Materai",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60186",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Dividen",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60187",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Tender",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60188",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Asosiasi",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60189",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya KTA dan KADIN",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60190",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Entertain",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60191",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Parkir",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60192",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPh Tax Amnesty",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60193",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban PPN",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60194",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Beban Penghapusan Piutang Tak Tertagih",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60195",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Komisi",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60196",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Jasa Pelayaran",
                kategori: "Beban",
                saldo: " ",
            },
            {
                kode_akun: "6-60197",
                nama: "Beban Administrasi dan Umum",
                nama_akun: "Biaya Pajak Bumi dan Bangunan",
                kategori: "Beban",
                saldo: " ",
            },
            ],

                skipDuplicates: true,
        })

        res.status(200).json({ message: 'success!', data: createManyDaftarAkun })
    } catch (error) {
        res.status(400).json({ kode_akun: 'error', error })
    }
}